### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Lj4040** [wyxstriker/LM-Combiner#1]
非常感谢您的工作。我想问下，您的代码什么时候会公布？想参考学习下

**Comment by wyxstriker** [comment]
我们会在本周内上传主要的代码和模型权重，感谢您对我们工作的关注。

**Comment by Lj4040** [comment]
好的，感谢您的回复

**Comment by macanv** [comment]
@wyxstriker  老师好，对该工作很感兴趣，请问什么时候可以公开权重和模型相关代码呀？

**Comment by wyxstriker** [comment]
抱歉，先前由于集群存储原因代码丢失，现已重新实现开源，感谢各位对本工作的关注。

**Comment by TLL1213** [comment]
非常感谢您的贡献，请问模型权重什么时候会发布呢
