### ISSUE TITLE
模型权重

### ISSUE THREAD

**Issue by TLL1213** [wyxstriker/LM-Combiner#3]
感谢您所做的贡献，请问一下，模型权重会发布出来吗？

**Comment by wyxstriker** [comment]
权重计划开源，但是主要是用于验证论文的实验结果。在真实场景下，每个校对系统的过度纠正分布是不一样的，直接使用本项目中基于Bart的LM-Combiner的效果肯定是不好的。如果想达到缓解当前系统过度纠正的效果，还得参考论文中的方式针对该系统构造对应的过度纠正数据进行训练才行。

**Comment by TLL1213** [comment]
非常感谢，请问计划什么时候开源呢，希望得到权重学习一下FCGEC上的一些分布。

**Comment by TLL1213** [comment]
> 权重计划开源，但是主要是用于验证论文的实验结果。在真实场景下，每个校对系统的过度纠正分布是不一样的，直接使用本项目中基于Bart的LM-Combiner的效果肯定是不好的。如果想达到缓解当前系统过度纠正的效果，还得参考论文中的方式针对该系统构造对应的过度纠正数据进行训练才行。

非常感谢，请问计划什么时候开源呢，希望得到权重学习一下FCGEC上的一些分布。

**Comment by wyxstriker** [comment]
FCGEC上单卡训练就非常快了，我把之前的权重放在[huggingface link](https://huggingface.co/DecoderImmortal/LM-Combiner)了，有问题欢迎交流讨论。
