### ISSUE TITLE
代码文件

### ISSUE THREAD

**Issue by YKinging** [wyxstriker/LM-Combiner#4]
代码里面有个文件在哪里呢，P, R, F5 = eval_main(f'./temp_predict_gpt.m2', '/share/home/chewanxiang/yxwang/cbart_cot/data/dev.m2.char')
        result = {
            "P": P,
            "R": R,
            "F05": F5
        }
        就是这个远程服务器上的文件，想复现您的代码

**Comment by wyxstriker** [comment]
抱歉整理代码时没有注意，这个文件是dev集M2形式的正确label，路径在`./data/fcgec/dev.m2.char`（已修复）。
对于其他数据集你可以：

- 一些数据集会开放M2格式的数据集；
- 利用[ChERRANT](https://github.com/HillZhang1999/MuCGEC/tree/main/scorers/ChERRANT)中的`parallel_to_m2.py`完成平行语料到M2的转换；
